### ISSUE TITLE
Render JSON without rendering @mt

### ISSUE THREAD

**Issue by cocowalla** [serilog/serilog-formatting-compact#14]
I have a feeling that perhaps I'm 'doing Serilog wrong', but what I'm trying to do is log a message along with a some JSON-formatted data, and my own correlation ID. For example, this is the output I'm looking for:

`{"@t":"2017-05-08T21:32:05.7713278Z","@m":"Oh noes!","@l":"Warning","@i":"bc5016e7-198c-4345-9735-b0c4003b5178","Properties":{"NodeId":"a1882552-17eb-42d1-b7cd-e895178167fb","ObjectName":"C:\\Windows\\System32\\something.exe","Other":"Other stuff here"}}`

No matter what combination of `JsonFormatter`/`CompactJsonFormatter`/`RenderedCompactJsonFormatter` and reified properties I use in my message template, I just can't get the desired output.

Is there some way to do what I'm looking for? That is, to exclude `@mt` from the output, outputting a `@m` message while _also_ outputting JSON?

**Comment by cocowalla** [comment]
I solved this by implementing my own `ITextFormatter`, based on this repo's `CompactJsonFormatter`.

**Comment by nblumhardt** [comment]
Great, thanks for the update. This sounds like the right approach 👍
