### ISSUE TITLE
CompactJsonFormatter is not working with Splunk EventCollection Sink

### ISSUE THREAD

**Issue by avireddy02** [serilog/serilog-formatting-compact#15]
CompactJsonFormatter is not working with Splunk EventCollection Sink. Looks like it's not generating Event attribute.

Error: A status code of BadRequest was received when attempting to send to http://localhost:8088/services/collector. The event has been discarded and will not be placed back in the queue.

**Comment by nblumhardt** [comment]
Hi @avireddy02 - I think this may be due more how the Splunk sink works than the compact JSON formatter itself. @merbla ?

**Comment by avireddy02** [comment]
Thanks for the update. I will create a bug under Splunk Sink repo.
