### ISSUE TITLE
Shorthand property name for SourceContext

### ISSUE THREAD

**Issue by snboisen** [serilog/serilog-formatting-compact#16]
Hi, I was looking at my Serilog message formatted by RenderedCompactJsonFormatter in my ELK instance and I noticed that SourceContext is not among the special short-named keys. 99.9% of my log messages will contain the SourceContext property and I would expect that to hold for most projects.

Would it make sense to add it to the list of compact keys as "@sc" or something?

**Comment by nblumhardt** [comment]
Thanks for the suggestion. I think this is worth considering, though I think we should probably hold any additions for a little while to try "batching up" improvements in a future revision of the format.

`@sc` would save 10 chars per event; `@s` would get this to 11 - but compete for primacy with `Scope` from ASP.NET Core.

**Comment by nblumhardt** [comment]
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) can do this, now.
