### ISSUE TITLE
Configuration flag for RenderedJsonFormatter

### ISSUE THREAD

**Issue by technophil98** [serilog/serilog-formatting-compact#17]
Is there a way to specify in the Serilog config that the desired format is **RenderedJsonFormatter**?
I know that in order to obtain it, we have to do a  `new JsonFormatter(renderMessage: true)` when configuring the sink.

The value for **CompactJsonFormatter** is:
`"Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"`.
Does the equivalent exist for **RenderedJsonFormatter**?

**Comment by nblumhardt** [comment]
Hi @technophil98 - the value is the assembly-qualified type name of the formatter, so in the case of the "rendered" version it's:

```
Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact
```

HTH,
Nick

**Comment by technophil98** [comment]
Thank you very much!
