### ISSUE TITLE
Configuration syntax for dotnet core appsettings.json

### ISSUE THREAD

**Issue by bradacina** [serilog/serilog-formatting-compact#23]
For an app targeting dotnet core 2.1 with appsettings.json config file, I'm trying the following config section but doesn't seem to work

`  "Serilog": {
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
        }
      }
    ]
  }`

Is the formatter supposed to be specified in the Args sub-section?

**Comment by tsimbalar** [comment]
Hi Bogdan,

I think you are missing a `"Using"` directive in your config file.

It should be : 

```json
"Serilog": { 
  "Using": [ "Serilog.Formatting.Compact" ],
  "WriteTo": [ 
    { 
      "Name": "Console", 
      "Args": { 
        "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact" 
      } 
    } 
  ] 
}
```

(and you need to install the `Serilog.Formatting.Compact` nuget package)

I hope this helps !

**Comment by bradacina** [comment]
It did. Thank you very much.
