### ISSUE TITLE
Add JSON config example in README

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-formatting-compact#24]
Related to #23 
Related to https://github.com/serilog/serilog-settings-configuration/issues/81

We have a config example using `appSettings`, it would be nice to have an example using *Serilog.Settings.Configuration*.

**Comment by Rabadash8820** [comment]
FYI, it looks like this Issue was supposed to be closed by #28

**Comment by nblumhardt** [comment]
Thanks 👍
