### ISSUE TITLE
Removing default values

### ISSUE THREAD

**Issue by EricStG** [serilog/serilog-formatting-compact#25]
Is there any way to remove default values from being logged? It would reduce our payloads quite significantly, especially for nullable types/

**Comment by nblumhardt** [comment]
Hi @EricStG - not with this formatter; however, you can plug an `ILogEventEnricher` into your logging pipeline via `Enrich.With(new MyCustomEnricher())` to achieve something similar.

Note that depending on where you send the data, you'll need to ensure any properties that are formatted into the message template, e.g. `Name` in `"Hello, {Name}"`, are preserved irrespective of whether or not the value is a default.

(If it's just one or two well-known properties that are taking up the space this should be pretty straightforward to write that way, too.)

HTH,
Nick

**Comment by EricStG** [comment]
Thanks @nblumhardt. Unfortunately, those payloads are vendor supplier and subject to changes. The object graph can be massive and have 90%+ null properties.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I think the types in the `Serilog.Data` namespace can help with this - you can rewrite nested objects using https://github.com/serilog/serilog/blob/dev/src/Serilog/Data/LogEventPropertyValueRewriter.cs if you decide that route's still worth exploring.

**Comment by EricStG** [comment]
Thanks, this looks promising! Silly question though, how does one connect a Rewriter to Serilog's configuration?

**Comment by nblumhardt** [comment]
It's usually plugged in as an `ILogEventEnricher` - `Enrich.With(new MyPropertyRewritingEnricher())` - HTH
