### ISSUE TITLE
Introduce a way to format Exceptions

### ISSUE THREAD

**Issue by oscarmorasu** [serilog/serilog-formatting-compact#26]
In your current implementation exceptions are formatted as "ex.ToString()".
It would be great to format the Exception as JSON, spitting out the Message, Type, Method and StackTrace as JSON properties. The StackTrace could be formatted as a JSON array, where each line is one string in the array. You can see that concept in action [in this PR](https://github.com/serilog/serilog-sinks-elasticsearch/pull/233).
This is extremelly helpful when aggregating exceptions by Type or Message in tools like Splunk.
I ended implementing this in my own ITextFormatter, but I think this should be part of the library.
If/when you decide to iterate on the JSON formatter, I would be more than happy to contribute with my solution.
Since Exceptions are a very important element of error logging, have you considered introducing an `IExceptionFormatter`, with a method `FormatException`, and sink authors could implement their own formatting (in this case JSON).

**Comment by nblumhardt** [comment]
Hi @oscarmorasu , thanks for the note. _SerilogExceptions_ is an add-on to Serilog that explores some of this space, and might be handy for you.

Unfortunately, in .NET, `Exception` is mutable, and is mutated when re-thrown. This makes it extremely difficult to deal with exception formatting nicely in sinks that work asynchronously. We have a couple of options for handling this and expect it'll be a part of "3.0" when that work eventually materializes (iterations on the core logging pipeline are deliberately very slow/conservative, but we'll do this eventually :-))

I think right now we can accept this as a data point, but can't move it forward in the short term.

Thanks!

**Comment by adamchester** [comment]
I'd like to add a +1 data point here too.

For example, I think it would be a great local development experience if the [console sink was able to easily highlight exceptions](https://github.com/adamchester/serilog-sinks-console/tree/spike-themed-exception), and I'd prefer not to have to re-parse them from the `ToString()` output, it would be nicer if Serilog captured them as immutable structured data in the first place.

**Comment by sungam3r** [comment]
@oscarmorasu I solved this problem with my own enrichers (essentially the same as _Serilog.Exceptions_).

**Comment by nblumhardt** [comment]
Hey all! I think https://github.com/serilog/serilog-expressions now provides a reasonable place to consider hooking in this kind of functionality. I don't think it's something we'd tackle in _Serilog.Expressions_.

Since it's a broad and tricky thing to get right I think it's best to close this and just consider specific proposals. Cheers!
