### ISSUE TITLE
Analogy Log Viewer Parser for this Formatting

### ISSUE THREAD

**Issue by LiorBanai** [serilog/serilog-formatting-compact#31]
Hi,
I have added a parser for this formatting base on your work:
https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog

just wanted to update in case people are still using this format since the reader repository seems not to be updated for some time :)

the parsing of the example:
![CompactFormat](https://user-images.githubusercontent.com/36262995/76024987-b5210680-5f34-11ea-8a83-4b893dcd3d92.jpg)

**Comment by nblumhardt** [comment]
Thanks, Lior! Looks great. A PR to add a note to the [Tools](https://github.com/serilog/serilog-formatting-compact#tools) section of the README would be welcome :+1:

**Comment by Rabadash8820** [comment]
FWIW, I think this Issue was supposed to be closed by #32

**Comment by nblumhardt** [comment]
👍

**Comment by LiorBanai** [comment]
BTW, I have added many improvements from that original post (both to Analogy Log Viewer and to Serilog parser itself) :)
