### ISSUE TITLE
Possibility to include both @m and @mt in json

### ISSUE THREAD

**Issue by videokojot** [serilog/serilog-formatting-compact#33]
Currently we can decide only either having the rendered message or the message template. For us it would be useful, to include both of those in the json, since it would tremendously simplified filtering and searching of logs in elastic search/kibana. It would allow us to easily filter out non interesting events by the message template, when digging in logs, while still keeping the benefit of having rendered message (better readibility).

**Comment by sungam3r** [comment]
I also asked such a question, but in the end I did not use @m in favor of @mt. Although your suggestion makes sense.

**Comment by nblumhardt** [comment]
@videokojot did you spot `@i` in the rendered version? It's usually enough to stand in for the message template (it's a hash of `@mt`). HTH!

**Comment by videokojot** [comment]
Sorry for late response. @nblumhardt thank you for the suggestion. That good for filtering, but not so much for the searching of the message. 

In the end we ended up copying-modifying the RenderedCompactJson and adding the @mt property.

https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/RenderedCompactJsonFormatter.cs

Thank you very much. Should I close?

**Comment by nblumhardt** [comment]
Thanks 👍

**Comment by nblumhardt** [comment]
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) can do this, now.
