### ISSUE TITLE
Is there a built-in way to combine JSON formatted events into a single JSON object (file) using Serilog?

### ISSUE THREAD

**Issue by christopherallanperry** [serilog/serilog-formatting-compact#35]
I'm working on a project that uses Serilog to create its log files in a JSON format. The idea is that (probably) once per day, the more human-readable aspects of the log files will be used as a source to generate an email to the system's user, giving them the detail of  any problems that have arisen.

Currently, I'm using the RenderedCompactJsonFormatter to pass events out to a log file, but they are recorded as individual JSON 'blobs', separated by a carriage return.

Does Serilog have a means by which a single JSON object, containing an array of event objects, can be generated per file?

**Comment by nblumhardt** [comment]
Hi Chris! No, there's no support like this built into Serilog. Working with newline-delimited JSON streams is your best bet, if possible. Reading the file line-by-line and then deserializing is the norm - check out _Serilog.Formatting.Compact.Reader_ if you're looking for a rough outline of how these files might be processed. HTH!

**Comment by christopherallanperry** [comment]
Thanks Nicholas,

I kind of had a feeling that was the case. I'll take a look at the Reader and see whether I can get what I'm looking for that way.

Chris
