### ISSUE TITLE
Custom mapping for context properties

### ISSUE THREAD

**Issue by joacar** [serilog/serilog-formatting-compact#37]
Hi,

What do you think about providing a way to configure compact keys for context properties? Consider
```json
{
	"@t": "2020-10-19T09:25:53.5767574Z",
	"@mt": "{Protocol} {Method} {RequestPath} {StatusCode} in {RequestDuration} ms",
// Inspired by Serilog middleware
	"Protocol": "HTTP/1.1",
	"Method": "GET",
	"StatusCode": 200,
	"RequestDuration": 23.5447,
// End inspired ...
	"SourceContext": "Namespace.Diagnostics.Hosting",
// Start HostingLoggerExtensions.cs HLE
	"RequestId": "0HM3FHOBGSJDL:0000204C",
	"RequestPath": "/metrics",
	"SpanId": "297e422451229e48",
	"TraceId": "1492670e02e7a8459a72c677fc9ce3be",
	"ParentId": "0000000000000000",
// End HLE
	"ConnectionId": "0HM3FHOBGSJDL"
}
```
>RequestPath added by [hosting](https://github.com/dotnet/aspnetcore/blob/f3f9a1cdbcd06b298035b523732b9f45b1408461/src/Hosting/Hosting/src/Internal/HostingLoggerExtensions.cs#L151) so it's reused to avoid additional properties.

I've implemented a diagnostics event listener to emit logs lines identical to those in [datalust middleware](https://github.com/datalust/serilog-middleware-example/blob/master/src/Datalust.SerilogMiddlewareExample/Diagnostics/SerilogMiddleware.cs).

**Comment by sungam3r** [comment]
#36 is the answer I think.

**Comment by nblumhardt** [comment]
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) is the way to go, now 👍
