### ISSUE TITLE
Add Ability to log timestamps in local time with offset

### ISSUE THREAD

**Issue by duanenewman** [serilog/serilog-formatting-compact#38]
Logging time in UTC by default is great and saves a few (5) bytes per log, but there may be cases (like mine) where I need to create the logs in local time so that timestamps line up with the machine time and don't require extra processing when viewed in a text editor or CLEF viewer.

Proposed change would be to add an optional Boolean parameter to the constructor with a default value of false that indicates logs should be written in local time with offset.

I have already created a modified version that accomplishes this, I will submit a pull request that enables this functionality if you want to merge it in.

**Comment by nblumhardt** [comment]
Thank you for the note and PR.

We're not pursuing any extensibility to this formatter, with the goals that a) the format remains somewhat standardized, and b) the code stays simple enough to be readily copied/pasted/modified for any required modification.

I think your current solution of maintaining a modified copy of the formatter is the way to go, but for a fully-configurable JSON formatting experience, you may be interested in the work currently being done over in https://github.com/serilog/serilog-expressions.

Using that library, your desired format can be implemented with:

```csharp
   // File, 
   WriteTo.File(new ExpressionTemplate(
      "{ {..@p, @t, @l: if @l = 'Information' then undefined() else @l, @mt, @x} }\n"), "log.ndjson")
```

Where `ExpressionTemplate` is an `ITextFormatter` just like `CompactJsonFormatter`.

Hope this helps,
Nick

**Comment by duanenewman** [comment]
@nblumhardt No worries, Just wanted to share the changes I made. Thanks for the example, I didn't know about `ExpressionTemplate` until now, I will probably switch to that!
