### ISSUE TITLE
Add built-in field name for EventId

### ISSUE THREAD

**Issue by Rabadash8820** [serilog/serilog-formatting-compact#40]
When using Serilog behind the `Microsoft.Extensions.Logging` facade, which I think is becoming the recommended best practice in .NET Core, one often includes an `EventId` in a log call:

```cs
_logger.LogInformation(new EventId(1001, "TransactionBegin"), "Beginning transaction {TrxnId}...", 12345);
```

When using this formatter with the File sink, one gets output like the following:

```log
{"@t":"2020-10-29T16:03:30.6943793Z","@mt":"Beginning transaction {TrxnId}...","EventId":{"Id":1001,"Name":"TransactionBegin"},"SourceContext":"MyNamespace.MyType","TrxnId":12345}
```

Because EventIDs are common with `Microsoft.Extensions.Logging`, I think it would be nice to recognize `EventId` as a built-in field, and shorten it to `@e` or `@ei`. Because `Id` and `Name` are nested JSON, you could also shorten them to `@i` and `@n`, thought that might require some JSON parsing that could slow down the formatter, idk. `"EventId" -> "@e"` would be the big one.

**Comment by sungam3r** [comment]
I don't think it's a good idea to use an external dependency and bind to its implementation.

**Comment by Rabadash8820** [comment]
@sungam3r You may be right; as I said, this just seems like an external dependency that is extremely common, and is only one additional condition in the parsing code.

That said, I only just read about `RenderedCompactJsonFormatter`'s `@i` property. That will probably meet the needs of my current project, but `@i` is still a Serilog-specific property. Having special handling for Microsoft's `EventId` would help all those developers who only want to use the logging functionality exposed by the Microsoft APIs.

**Comment by sungam3r** [comment]
See https://github.com/serilog/serilog-formatting-compact/pull/39#issuecomment-714754488

**Comment by nblumhardt** [comment]
Hi @Rabadash8820 - thanks for the note. As @sungam3r suggests, the format produced by this library is Serilog-specific and essentially closed to modification; we've been working on [an alternative that's highly-configurable](https://github.com/serilog/serilog-expressions#formatting) and can do the `@i`/`@n` breakdown you suggest:

```csharp
    .WriteTo.File(new ExpressionTemplate(
        "{ {@t, @mt, @i: EventId.Id, @n: EventId.Name, @l: if @l = 'Information' then undefined() else @l, @x, ..@p} }\n"),
        "./log.ndjson")
```

Would be great to hear whether this does the trick for you.

**Comment by Rabadash8820** [comment]
@nblumhardt @sungam3r Thanks for the links. I'm a bit wary of Expressions from what I've seen, just cause it looks like a lot of "stringly typed" code, but I'll give them a try. Between those and the native `@i` property on `RenderedCompactJsonFormatter`, I think I will have what I need.

This might warrant a separate Issue, but is there any reason why `CompactJsonFormatter` (non-rendered) doesn't also have an `@i` property?

**Comment by nblumhardt** [comment]
@Rabadash8820 thanks for the follow-up. `CompactJsonFormatter` carries `@mt`, which plays effectively the same role as `@i`.

**Comment by Rabadash8820** [comment]
Ah, that does make sense. Though it would be kinda nice to have the additional Id there as an "alias" to make queries shorter in systems like Elastic search, without incurring the additional "rendering" cost of `RenderedCompactJsonFormatter`.

**Comment by nblumhardt** [comment]
:+1: Serilog.Expressions will eventually cover this requirement.
