### ISSUE TITLE
Why Information levels are ommited? 

### ISSUE THREAD

**Issue by abenedykt** [serilog/serilog-formatting-compact#41]
https://github.com/serilog/serilog-formatting-compact/blob/1eca9e524cb8b2abc32b08ef1e3f87fed6762f73/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs#L90

**Comment by sungam3r** [comment]
This is done to save a little on message size. Apparently, the expectations were that messages with the `Information` level are the main ones for the application.

**Comment by nblumhardt** [comment]
Thanks for the note. This is a duplicate of  #13, #19, and #20, with discussion in those threads.

**Comment by nblumhardt** [comment]
[JSON formatting with `ExpressionTemplate`](https://github.com/serilog/serilog-expressions#formatting-with-expressiontemplate) can do this, now.
