### ISSUE TITLE
Allow overrides for @mt and @t

### ISSUE THREAD

**Issue by ardove** [serilog/serilog-formatting-compact#42]
We have an entire custom formatter to rename @mt to MSG and @t to TS. It'd be great if we could just ditch that code altogether and have a mechanism for renaming the properties in the compact json formatter.

**Comment by sungam3r** [comment]
https://github.com/serilog/serilog-formatting-compact/issues/40#issuecomment-719813271
https://github.com/serilog/serilog-formatting-compact/pull/39#issuecomment-714754488

**Comment by ardove** [comment]
Sorry, just so I'm clear @sungam3r , you're suggesting that I use an expression template to make this work the way I want it to? And that will support all the automatic stuff I'm used to (like automatically including properties at the same level as the rest of the properties in the rendered json blob)?

**Comment by sungam3r** [comment]
I want to say that this repo will not change with 100% probability.

**Comment by ardove** [comment]
OK, thanks. I guess we'll just implement our own log event formatter.

**Comment by nblumhardt** [comment]
@ardove the `ExpressionTemplate` route looks something like this:

```csharp
    .WriteTo.Console(new ExpressionTemplate(
          "{ {TS: @t, MSG: @mt, @l: if @l = 'Information' then undefined() else @l, @x, ..@p} }" + Environment.NewLine)))
```
