### ISSUE TITLE
Won't compile when referencing Serilog.Formatting.Compact in Azure DevOps

### ISSUE THREAD

**Issue by LukeHersman** [serilog/serilog-formatting-compact#47]
Hi!

I have an application that is built in Azure DevOps. When just adding Serilog and a few sinks, everything was fine. However, I went to add `Serilog.Formatting.Compact` so that I could try out `CompactJsonFormatter()` and when I do it suddenly breaks the build. Worth noting everything builds fine on my dev machine; only breaks on Azure DevOps using [vmImage: windows-2019](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)

**Error Log:**
`Program.cs(26,26): Error CS0234: The type or namespace name 'Compact' does not exist in the namespace 'Serilog.Formatting' (are you missing an assembly reference?)`

**Code:**
line 26: `using Serilog.Formatting.Compact;`

**Comment by nblumhardt** [comment]
Hi @LukeHersman, unfortunately this one will be an environment issue unrelated to the project itself. There's not much we can do to help, but good luck with it!
