### ISSUE TITLE
Question: Is it possible to camelcase the properties?

### ISSUE THREAD

**Issue by joseftw** [serilog/serilog-formatting-compact#49]
Hello!

Thank you for an awesome lib!

Is it possible somehow to camelcase the outputed json properties?

Current:

```csharp
{"@t":"2016-06-07T03:44:57.8532799Z","@mt":"Hello, {User}","User":"nblumhardt"}
```

Wanted (note the small **u** on **user**):
```csharp
{"@t":"2016-06-07T03:44:57.8532799Z","@mt":"Hello, {User}","user":"nblumhardt"}
```

**Comment by nblumhardt** [comment]
Hi! Copying this small class into your project:

https://github.com/serilog/serilog-formatting-compact/blob/dev/src/Serilog.Formatting.Compact/Formatting/Compact/CompactJsonFormatter.cs

and modifying line 113 would be the easiest way to go.

`CompactJsonFormatter` is a very thin wrapper around `JsonValueFormatter` from Serilog core that does most of the heavy lifting.

**Comment by joseftw** [comment]
Thank you! :)
