### ISSUE TITLE
Optionally ignore null fields

### ISSUE THREAD

**Issue by squideyes** [serilog/serilog-formatting-compact#50]
Hi!  It would be great if the compact formatter could optionally ignore null fields

**Comment by nblumhardt** [comment]
Hi! Serilog.Formatting.Compact is intended to be a minimal/configuration-free library - this makes it very light and easy to copy and modify to your requirements, or, if you want a fully-configurable formatting experience, check out Serilog.Expressions and some recipes that might hint at ways to implement what you need:

 * https://nblumhardt.com/2021/06/customize-serilog-json-output/
 * https://github.com/serilog/serilog-expressions

Cheers!
Nick
