### ISSUE TITLE
RenderedCompactJsonFormatter doesn't allow control of Exception format

### ISSUE THREAD

**Issue by gw79** [serilog/serilog-formatting-compact#51]
[Line 83 of RenderedCompactJsonFormatter](https://github.com/serilog/serilog-formatting-compact/blob/8393e0ab8c2bc746fc733a4f20731b9e1f20f811/src/Serilog.Formatting.Compact/Formatting/Compact/RenderedCompactJsonFormatter.cs#L83) does a .ToString() call on LogEvent.Exception if not null.

I have an issue whereby our Splunk back-end has a limit to the number of characters in an event message (which sadly also includes the extra fluff Windows Event Log adds - company standard dictates logs are forwarded from Event Log.)

When an Exception gets logged in our aspnetcore applications the StackTrace is invariably quite long, due to the many call stack frames added by layers of framework code plus our own middleware and Controller/Domain/Infrastructure code.

I would like to have control over the rendered output of the LogEvent.Exception property, but since the property is read-only I can't replace it via an enricher, so at the moment it seems near impossible without editing RenderedCompactJsonFormatter or adding my own implementation of ILogger.

Please advise - is this achievable via some other means such as Expressions?

Aside from this I quite like RenderedCompactJsonFormatter, it does a good job of saving space with the abbreviated prop names, but seems it lacks a bit of extensibility.

**Comment by nblumhardt** [comment]
Hi! Copying the source of RenderedCompactJsonFormatter.cs into your project is probably the quickest/easiest way to achieve this, but with _Expressions_ you can also do:

```csharp
    .WriteTo.Console(new ExpressionTemplate(
        "{ {@t, @i, @m, @l: if @l = 'Information' then undefined() else @l, @x: Substring(@x, 0, 1234), ..@p} }\n",
        theme: TemplateTheme.Code))
```

HTH!

**Comment by gw79** [comment]
Great thanks for the quick response Nicholas. Yep I took a copy of the
code, subclassed JsonValueFormatter to add a FormatException method, it'll
do!

Is Expressions fully supported for all sinks and appsettings.json? Examples
are all in code with Console, we use appsettings and Event Log

**Comment by nblumhardt** [comment]
👍 great! Yes, `ExpressionTemplate` implements Serilog's `ITextFormatter` interface, which can be plugged into practically all sinks that output text.

Here's an example of appsettings.json usage: https://github.com/serilog/serilog-settings-configuration/#complex-parameter-value-binding
