### ISSUE TITLE
using of RenderedCompactJsonFormatter in XML for the version 2.0.0 in Dotnet framework 4.8 make System.MissingMethodException

### ISSUE THREAD

**Issue by NasraouiaMohamed** [serilog/serilog-formatting-compact#63]
i did upgrade for the Serilog.Formatting.Compact to version 2.0.0 in my console application (dotnet framework 4.8)
i'm using this line in my app.config file that is the reason of the issue: 

![image](https://github.com/serilog/serilog-formatting-compact/assets/33115220/ceb9b45a-8edb-48c2-8e20-a6a7e65e0276)

and i get this error
**System.MissingMethodException: Method not found: 'System.Nullable`1<System.Diagnostics.ActivityTraceId> Serilog.Events.LogEvent.get_TraceId()'.**

![image](https://github.com/serilog/serilog-formatting-compact/assets/33115220/247a391f-2fa3-4ecd-bd8d-7ccf520bc0f8)

**Comment by NasraouiaMohamed** [comment]
the reason of this issue i think that the new version 2.0.0 use System.Diagnostics.ActivityTraceId that is not supported in .net framework 4.8.
so what can be the solution PLZ?

**Comment by nblumhardt** [comment]
Sounds like you might have a v2.x Serilog.dll in your GAC? v4 will sort this out, but GAC'ing 3.1.1 should also resolve it. HTH!

**Comment by NasraouiaMohamed** [comment]
can you tell me please what i have to do in this case?
