### ISSUE TITLE
how to remove $type property ?

### ISSUE THREAD

**Issue by spointeau** [serilog/serilog-formatting-compact#64]
Hi, 

please could you point me out how to remove the $type property in CompactJsonFormatter ?

Best regards,
Sylvain

**Comment by nblumhardt** [comment]
Hi @spointeau! Passing a `JsonValueFormatter` with `null` type tag name will do this:

```csharp
    new CompactJsonFormatter(new JsonValueFormatter(null))
```

Let me know if this does the trick!

Best regards,
Nick

**Comment by spointeau** [comment]
I tried this yes, but nothing changed ...

**Comment by nblumhardt** [comment]
Here it is working for me:

![image](https://github.com/serilog/serilog-formatting-compact/assets/342712/c92c2a75-7ecf-48e2-bc34-002c3ab78e80)

**Comment by spointeau** [comment]
does it work also when using ForContext() with destructure = true ?
(I only tested this case)

**Comment by nblumhardt** [comment]
Yes, exactly the same difference in output here :+1:

**Comment by spointeau** [comment]
@nblumhardt I retested and it also works for me. I even found out the logs from Friday that it also worked previously (Friday). My deep apologies to have made you lost your time here.

**Comment by nblumhardt** [comment]
That's no problem at all - happy to help :+1:
