### ISSUE TITLE
Compact Log Event Format (CLEF) - log4j config file

### ISSUE THREAD

**Issue by amosshi** [serilog/serilog-formatting-compact#69]
Hello serilog, 

We love the **Compact Log Event Format (CLEF)** which will generate smaller log outputs, since
- it will save resources for big applications 
- and save license cost for log processing software who charged based on logging traffic size.

Based on
- https://github.com/apache/logging-log4j2/issues/3207

We would like to contribute CLEF to deliver a log4j2 layout template like the files here
- https://github.com/apache/logging-log4j2/tree/2.x/log4j-layout-template-json/src/main/resources

Need your advise how we may do it, like you create a repo under https://github.com/serilog and we will provide PR, and finally deliver it to maven central.

thanks
Amos
A Happy Developer

**Comment by nblumhardt** [comment]
Hi @amosshi, thanks for reaching out! Sounds great, but this project is the Serilog logging library for .NET and this would be outside the scope of what we would publish here.

The best option for publishing is likely to be through your own GitHub profile and Maven Central account; if you decide to give this a shot, please send a PR to list it in the directory over in https://github.com/clef-json/clef-json.github.io/edit/main/README.md :-)

All the best,
Nick
