### ISSUE TITLE
Can we create an option that lets us change the @ prefix to another/other character/s?

### ISSUE THREAD

**Issue by jgtestw** [serilog/serilog-formatting-compact#70]
We are sending logs to CloudWatch. Unfortunately, CloudWatch doesn't let you create "metric filters" for properties that start with `@`. If I submit a pull request implementing a feature allowing you to swap the `@` with something else, it is likely to be accepted?  I guess my question is, is there some fundamental reason why we can't use a character other than `@`? If not, it seems like quite a trivial change.

**Comment by nblumhardt** [comment]
Hi! Serilog.Expressions is the intended solution for this; check out https://nblumhardt.com/2021/06/customize-serilog-json-output/ for some recipes that should get you pretty close to optimal for CloudWatch. HTH!
